In [1]:
import torch 
import numpy as np
import torchvision

In [2]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [3]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

In [4]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [6]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [6]:
tensor = torch.rand(2, 2)
print(tensor)

tensor([[0.5380, 0.9776],
        [0.3663, 0.3875]])


In [7]:
print(tensor + tensor)
print(tensor * tensor)

tensor([[1.0760, 1.9551],
        [0.7326, 0.7751]])
tensor([[0.2895, 0.9556],
        [0.1342, 0.1502]])


In [8]:
tensor = torch.rand(1000, 1000) 
tensor.matmul(tensor.T)

tensor([[356.0289, 259.4393, 259.9976,  ..., 268.1339, 261.7565, 270.4874],
        [259.4393, 331.5832, 247.6438,  ..., 254.6568, 253.1635, 258.3434],
        [259.9976, 247.6438, 334.7607,  ..., 257.5806, 253.9530, 255.6121],
        ...,
        [268.1339, 254.6568, 257.5805,  ..., 342.2781, 264.5026, 262.0823],
        [261.7565, 253.1636, 253.9530,  ..., 264.5026, 347.5656, 261.9825],
        [270.4874, 258.3434, 255.6121,  ..., 262.0823, 261.9825, 348.3051]])

In [9]:
tensor = torch.rand(3, 4)
tensor.add_(5)
print(tensor)

tensor([[5.4484, 5.8294, 5.8123, 5.7519],
        [5.6575, 5.3059, 5.5248, 5.9924],
        [5.7652, 5.5874, 5.5586, 5.3188]])


In [10]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [11]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [12]:
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [23]:
prediction = model(data) # forward pass
prediction

tensor([[-4.8451, -4.9175, -4.7626, -5.7902, -5.2996, -4.6637, -4.7945, -4.0148,
         -4.0001, -5.8622, -5.3986, -5.1339, -4.7566, -5.5330, -5.5971, -4.7801,
         -5.0582, -4.7883, -5.0481, -4.9423, -5.8758, -4.9866, -5.7600, -4.2509,
         -5.1759, -5.5144, -5.3117, -5.4980, -5.3330, -4.9205, -5.0453, -5.3611,
         -4.8221, -4.9153, -4.8301, -4.9271, -3.7658, -5.0371, -5.0968, -4.4300,
         -5.2577, -5.3010, -5.5412, -4.7896, -5.1432, -4.6451, -5.4196, -5.3022,
         -5.2977, -5.9018, -4.7799, -3.9067, -4.8257, -4.9389, -4.4617, -5.7653,
         -4.5899, -5.8080, -4.8183, -5.0241, -3.8475, -4.3281, -4.6338, -4.4357,
         -5.5714, -4.7774, -4.9386, -4.7157, -5.2462, -5.6890, -6.2341, -4.3597,
         -6.0955, -5.2096, -5.7599, -5.7676, -4.4058, -5.2988, -4.4317, -4.7542,
         -5.4041, -5.7202, -4.1892, -5.0231, -5.2623, -4.4428, -4.0437, -4.0106,
         -4.4727, -5.2436, -5.5400, -5.5595, -6.1655, -4.7867, -4.4694, -6.6098,
         -5.1571, -4.6249, -

tensor(6.)